Matrix Class Reference
Write what the function does here.
#include <matrix.h>
Public Member Functions
float get (const int x, const int y) const
Write what the function does here.
void set (const int x, const int y, float value)
Write what the function does here.
Matrix (float x00, float x10, float x20, float x30, float x01, float x11, float x21, float x31, float x02, float x12, float x22, float x32)
Matrix ()
Write what the function does here.
float determinant () const
Write what the function does here.
Matrix invert () const
Write what the function does here.
Matrix concat (Matrix rt) const
Write what the function does here.
VectorF apply (VectorF v) const
Write what the function does here.
VectorF applyToNormal (VectorF v) const
Write what the function does here.
Static Public Member Functions
static Matrix identity ()
Write what the function does here.
static Matrix rotate (const VectorF axis, const double angle)
Write what the function does here.
static Matrix rotateX (double angle)
Write what the function does here.
static Matrix rotateY (double angle)
Write what the function does here.
static Matrix rotateZ (double angle)
Write what the function does here.
static Matrix translate (VectorF position)
Write what the function does here.
static Matrix translate (float x, float y, float z)
Write what the function does here.
static Matrix scale (float x, float y, float z)
Write what the function does here.
static Matrix scale (VectorF s)
Write what the function does here.
static Matrix scale (float s)
Write what the function does here.
static Matrix thetaPhi (double theta, double phi)
Write what the function does here.
Public Attributes
float x00
float x10
float x20
float x30
float x01
float x11
float x21
float x31
float x02
float x12
float x22
float x32
Friends
Matrix inverse (const Matrix &m)
Write what the function does here.
Detailed Description
Write what the function does here.
4x4 matrix for 3D transformation with last row always equal to [0 0 0 1]
Author
jacob
Returns
Definition at line 14 of file matrix.h.
Constructor & Destructor Documentation
Matrix::Matrix (float x00, float x10, float x20, float x30, float x01, float x11, float x21, float x31, float x02, float x12, float x22, float x32) [inline]
Parameters
x32 Write what the function does here
x32
Returns
Definition at line 241 of file matrix.h.
        {
            this->x00 = x00;
            this->x10 = x10;
            this->x20 = x20;
            this->x30 = x30;
            this->x01 = x01;
            this->x11 = x11;
            this->x21 = x21;
            this->x31 = x31;
            this->x02 = x02;
            this->x12 = x12;
            this->x22 = x22;
            this->x32 = x32;
        }
Matrix::Matrix () [inline]
Write what the function does here.
Returns
Definition at line 281 of file matrix.h.
Referenced by concat(), identity(), invert(), rotate(), scale(), and translate().
        {
            this->x00 = 1;
            this->x10 = 0;
            this->x20 = 0;
            this->x30 = 0;
            this->x01 = 0;
            this->x11 = 1;
            this->x21 = 0;
            this->x31 = 0;
            this->x02 = 0;
            this->x12 = 0;
            this->x22 = 1;
            this->x32 = 0;
        }
Member Function Documentation
VectorF Matrix::apply (VectorF v) const [inline]
Write what the function does here.
Parameters
v
Returns
Definition at line 616 of file matrix.h.
        {
            return VectorF(v.x * this->x00 + v.y * this->x10 + v.z * this->x20
                    + this->x30, v.x * this->x01 + v.y * this->x11 + v.z * this->x21
                    + this->x31, v.x * this->x02 + v.y * this->x12 + v.z * this->x22
                    + this->x32);
        }
VectorF Matrix::applyToNormal (VectorF v) const [inline]
Write what the function does here.
Parameters
v
Returns
Definition at line 631 of file matrix.h.
        {
            return normalize(VectorF(v.x * this->x00 + v.y * this->x10 + v.z * this->x20, v.x
                        * this->x01 + v.y * this->x11 + v.z * this->x21, v.x * this->x02
                        + v.y * this->x12 + v.z * this->x22));
        }
Matrix Matrix::concat (Matrix rt) const [inline]
Write what the function does here.
Parameters
rt
Returns
Definition at line 592 of file matrix.h.
References Matrix().
Referenced by thetaPhi().
        {
            return Matrix(this->x00 * rt.x00 + this->x01 * rt.x10 + this->x02
                    * rt.x20, this->x10 * rt.x00 + this->x11 * rt.x10 + this->x12
                    * rt.x20, this->x20 * rt.x00 + this->x21 * rt.x10 + this->x22
                    * rt.x20, this->x30 * rt.x00 + this->x31 * rt.x10 + this->x32
                    * rt.x20 + rt.x30, this->x00 * rt.x01 + this->x01 * rt.x11
                    + this->x02 * rt.x21, this->x10 * rt.x01 + this->x11 * rt.x11
                    + this->x12 * rt.x21, this->x20 * rt.x01 + this->x21 * rt.x11
                    + this->x22 * rt.x21, this->x30 * rt.x01 + this->x31 * rt.x11
                    + this->x32 * rt.x21 + rt.x31, this->x00 * rt.x02 + this->x01
                    * rt.x12 + this->x02 * rt.x22, this->x10 * rt.x02 + this->x11
                    * rt.x12 + this->x12 * rt.x22, this->x20 * rt.x02 + this->x21
                    * rt.x12 + this->x22 * rt.x22, this->x30 * rt.x02 + this->x31
                    * rt.x12 + this->x32 * rt.x22 + rt.x32);
        }
float Matrix::determinant () const [inline]
Write what the function does here.
Returns
the determinant of this matrix
Definition at line 524 of file matrix.h.
Referenced by invert().
        {
            return this->x00 * (this->x11 * this->x22 - this->x12 * this->x21)
                + this->x10 * (this->x02 * this->x21 - this->x01 * this->x22)
                + this->x20 * (this->x01 * this->x12 - this->x02 * this->x11);
        }
float Matrix::get (const int x, const int y) const [inline]
Write what the function does here.
Parameters
x
y
Returns
Write what the function does here
Parameters
x
Returns
Write what the function does here
Parameters
y
Returns
Write what the function does here
Parameters
y
Returns
Write what the function does here
Parameters
y
Returns
Write what the function does here
Parameters
y
Returns
Definition at line 29 of file matrix.h.
        {
            /**
             * @brief Write what the function does here
             *
             * @param x
             *
             * @return
             **/
            switch(x)
            {
                case 0:
                    /**
                     * @brief Write what the function does here
                     *
                     * @param y
                     *
                     * @return
                     **/
                    switch(y)
                    {
                        case 0:
                            return this->x00;
                        case 1:
                            return this->x01;
                        case 2:
                            return this->x02;
                        default:
                            return x == y ? 1 : 0;
                    }
                case 1:
                    /**
                     * @brief Write what the function does here
                     *
                     * @param y
                     *
                     * @return
                     **/
                    switch(y)
                    {
                        case 0:
                            return this->x10;
                        case 1:
                            return this->x11;
                        case 2:
                            return this->x12;
                        default:
                            return x == y ? 1 : 0;
                    }
                case 2:
                    /**
                     * @brief Write what the function does here
                     *
                     * @param y
                     *
                     * @return
                     **/
                    switch(y)
                    {
                        case 0:
                            return this->x20;
                        case 1:
                            return this->x21;
                        case 2:
                            return this->x22;
                        default:
                            return x == y ? 1 : 0;
                    }
                case 3:
                    /**
                     * @brief Write what the function does here
                     *
                     * @param y
                     *
                     * @return
                     **/
                    switch(y)
                    {
                        case 0:
                            return this->x30;
                        case 1:
                            return this->x31;
                        case 2:
                            return this->x32;
                        default:
                            return x == y ? 1 : 0;
                    }
                default:
                    return x == y ? 1 : 0;
            }
        }
static Matrix Matrix::identity () [inline], [static]
Write what the function does here.
Returns
Definition at line 302 of file matrix.h.
References Matrix().
        {
            return Matrix(1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0);
        }
Matrix Matrix::invert () const [inline]
Write what the function does here.
Returns
the inverse of this matrix.
Definition at line 537 of file matrix.h.
References determinant(), and Matrix().
        {
            float det = determinant();
            if(det == 0.0f)
                throw domain_error("can't invert singular matrix");
            float factor = 1.0f / det;
            return Matrix((this->x11 * this->x22 - this->x12 * this->x21) * factor,
                    (this->x12 * this->x20 - this->x10 * this->x22) * factor,
                    (this->x10 * this->x21 - this->x11 * this->x20) * factor,
                    (-this->x10 * this->x21 * this->x32 + this->x11
                     * this->x20 * this->x32 + this->x10 * this->x22
                     * this->x31 - this->x12 * this->x20 * this->x31
                     - this->x11 * this->x22 * this->x30 + this->x12
                     * this->x21 * this->x30)
                    * factor,
                    (this->x02 * this->x21 - this->x01 * this->x22) * factor,
                    (this->x00 * this->x22 - this->x02 * this->x20) * factor,
                    (this->x01 * this->x20 - this->x00 * this->x21) * factor,
                    (this->x00 * this->x21 * this->x32 - this->x01 * this->x20
                     * this->x32 - this->x00 * this->x22 * this->x31
                     + this->x02 * this->x20 * this->x31 + this->x01
                     * this->x22 * this->x30 - this->x02 * this->x21
                     * this->x30)
                    * factor,
                    (this->x01 * this->x12 - this->x02 * this->x11) * factor,
                    (this->x02 * this->x10 - this->x00 * this->x12) * factor,
                    (this->x00 * this->x11 - this->x01 * this->x10) * factor,
                    (-this->x00 * this->x11 * this->x32 + this->x01
                     * this->x10 * this->x32 + this->x00 * this->x12
                     * this->x31 - this->x02 * this->x10 * this->x31
                     - this->x01 * this->x12 * this->x30 + this->x02
                     * this->x11 * this->x30)
                        * factor);
        }
static Matrix Matrix::rotate (const VectorF axis, const double angle) [inline], [static]
Write what the function does here.
creates a rotation matrix
Parameters
axis axis to rotate around
angle angle to rotate in radians
Returns
the new rotation matrix
See also
rotateX(double angle)
rotateY(double angle)
rotateZ(double angle)
Parameters
axis
angle
Returns
Definition at line 325 of file matrix.h.
References Matrix().
Referenced by rotateX(), rotateY(), and rotateZ().
        {
            VectorF axisv = normalize(axis);
            float c, s, v;
            c = cos(angle);
            s = sin(angle);
            v = 1 - c; // Versine
            float xx, xy, xz, yy, yz, zz;
            xx = axisv.x * axisv.x;
            xy = axisv.x * axisv.y;
            xz = axisv.x * axisv.z;
            yy = axisv.y * axisv.y;
            yz = axisv.y * axisv.z;
            zz = axisv.z * axisv.z;
            return Matrix(xx + (1 - xx) * c, xy * v - axisv.z * s, xz * v
                    + axisv.y * s, 0, xy * v + axisv.z * s, yy + (1 - yy) * c, yz
                    * v - axisv.x * s, 0, xz * v - axisv.y * s, yz * v + axisv.x
                    * s, zz + (1 - zz) * c, 0);
        }
static Matrix Matrix::rotateX (double angle) [inline], [static]
Write what the function does here.
creates a rotation matrix
 the same as Matrix::rotate(VectorF(1, 0, 0), angle)
Parameters
angle angle to rotate around the x axis in radians
Returns
the new rotation matrix
See also
rotate(VectorF axis, double angle)
rotateY(double angle)
rotateZ(double angle)
Parameters
angle
Returns
Definition at line 361 of file matrix.h.
References rotate().
Referenced by thetaPhi().
        {
            return rotate(VectorF(1, 0, 0), angle);
        }
static Matrix Matrix::rotateY (double angle) [inline], [static]
Write what the function does here.
creates a rotation matrix
 the same as Matrix::rotate(VectorF(0, 1, 0), angle)
Parameters
angle angle to rotate around the y axis in radians
Returns
the new rotation matrix
See also
rotate(VectorF axis, double angle)
rotateX(double angle)
rotateZ(double angle)
Parameters
angle
Returns
Definition at line 382 of file matrix.h.
References rotate().
Referenced by thetaPhi().
        {
            return rotate(VectorF(0, 1, 0), angle);
        }
static Matrix Matrix::rotateZ (double angle) [inline], [static]
Write what the function does here.
creates a rotation matrix
 the same as Matrix::rotate(VectorF(0, 0, 1), angle)
Parameters
angle angle to rotate around the z axis in radians
Returns
the new rotation matrix
See also
rotate(VectorF axis, double angle)
rotateX(double angle)
rotateY(double angle)
Parameters
angle
Returns
Definition at line 403 of file matrix.h.
References rotate().
        {
            return rotate(VectorF(0, 0, 1), angle);
        }
static Matrix Matrix::scale (float x, float y, float z) [inline], [static]
Write what the function does here.
creates a scaling matrix
Parameters
x the amount to scale the x coordinate by
y the amount to scale the y coordinate by
z the amount to scale the z coordinate by
Returns
the new scaling matrix
Parameters
x
y
z
Returns
Definition at line 477 of file matrix.h.
References Matrix().
Referenced by GUILabel::render().
        {
            return Matrix(x, 0, 0, 0, 0, y, 0, 0, 0, 0, z, 0);
        }
static Matrix Matrix::scale (VectorF s) [inline], [static]
Write what the function does here.
creates a scaling matrix
Parameters
s s.x is the amount to scale the x coordinate by.
 s.y is the amount to scale the y coordinate by.
 s.z is the amount to scale the z coordinate by.
Returns
the new scaling matrix
Parameters
s
Returns
Definition at line 496 of file matrix.h.
References Matrix().
        {
            return Matrix(s.x, 0, 0, 0, 0, s.y, 0, 0, 0, 0, s.z, 0);
        }
static Matrix Matrix::scale (float s) [inline], [static]
Write what the function does here.
creates a scaling matrix
Parameters
s the amount to scale by
Returns
the new scaling matrix
Parameters
s
Returns
Definition at line 513 of file matrix.h.
References Matrix().
        {
            return Matrix(s, 0, 0, 0, 0, s, 0, 0, 0, 0, s, 0);
        }
void Matrix::set (const int x, const int y, float value) [inline]
Write what the function does here.
Parameters
x
y
value
Write what the function does here
Parameters
x
Returns
Write what the function does here
Parameters
y
Returns
Write what the function does here
Parameters
y
Returns
Write what the function does here
Parameters
y
Returns
Write what the function does here
Parameters
y
Returns
Definition at line 133 of file matrix.h.
        {
            /**
             * @brief Write what the function does here
             *
             * @param x
             *
             * @return
             **/
            switch(x)
            {
                case 0:
                    /**
                     * @brief Write what the function does here
                     *
                     * @param y
                     *
                     * @return
                     **/
                    switch(y)
                    {
                        case 0:
                            this->x00 = value;
                            return;
                        case 1:
                            this->x01 = value;
                            return;
                        case 2:
                            this->x02 = value;
                            return;
                        default:
                            return;
                    }
                case 1:
                    /**
                     * @brief Write what the function does here
                     *
                     * @param y
                     *
                     * @return
                     **/
                    switch(y)
                    {
                        case 0:
                            this->x10 = value;
                            return;
                        case 1:
                            this->x11 = value;
                            return;
                        case 2:
                            this->x12 = value;
                            return;
                        default:
                            return;
                    }
                case 2:
                    /**
                     * @brief Write what the function does here
                     *
                     * @param y
                     *
                     * @return
                     **/
                    switch(y)
                    {
                        case 0:
                            this->x20 = value;
                            return;
                        case 1:
                            this->x21 = value;
                            return;
                        case 2:
                            this->x22 = value;
                            return;
                        default:
                            return;
                    }
                case 3:
                    /**
                     * @brief Write what the function does here
                     *
                     * @param y
                     *
                     * @return
                     **/
                    switch(y)
                    {
                        case 0:
                            this->x30 = value;
                            return;
                        case 1:
                            this->x31 = value;
                            return;
                        case 2:
                            this->x32 = value;
                            return;
                        default:
                            return;
                    }
                default:
                    return;
            }
        }
static Matrix Matrix::thetaPhi (double theta, double phi) [inline], [static]
Write what the function does here.
Parameters
theta
phi
Returns
Definition at line 646 of file matrix.h.
References concat(), rotateX(), and rotateY().
        {
            Matrix t = rotateX(-phi);
            return rotateY(theta).concat(t);
        }
static Matrix Matrix::translate (VectorF position) [inline], [static]
Write what the function does here.
creates a translation matrix
Parameters
position the position to translate (0, 0, 0) to
Returns
the new translation matrix
Parameters
position
Returns
Definition at line 420 of file matrix.h.
References Matrix().
Referenced by GUILabel::render().
        {
            return Matrix(1,
                    0,
                    0,
                    position.x,
                    0,
                    1,
                    0,
                    position.y,
                    0,
                    0,
                    1,
                    position.z);
        }
static Matrix Matrix::translate (float x, float y, float z) [inline], [static]
Write what the function does here.
creates a translation matrix
Parameters
x the x coordinate to translate (0, 0, 0) to
y the y coordinate to translate (0, 0, 0) to
z the z coordinate to translate (0, 0, 0) to
Returns
the new translation matrix
Parameters
x
y
z
Returns
Definition at line 454 of file matrix.h.
References Matrix().
        {
            return Matrix(1, 0, 0, x, 0, 1, 0, y, 0, 0, 1, z);
        }
Friends And Related Function Documentation
Matrix inverse (const Matrix & m) [friend]
Write what the function does here.
Returns
the inverse of this matrix.
Parameters
m
Returns
Definition at line 580 of file matrix.h.
        {
            return m.invert();
        }
The documentation for this class was generated from the following file:
matrix.h