Mesh_t::const_iterator Class Reference
Write what the function does here.
#include <mesh.h>
Public Member Functions
const_iterator ()
Write what the function does here.
bool operator== (const const_iterator &rt) const
Write what the function does here.
bool operator!= (const const_iterator &rt) const
Write what the function does here.
const Triangle & operator* () const
Write what the function does here.
const Triangle & operator[] (ssize_t index) const
Write what the function does here.
const Triangle * operator-> () const
Write what the function does here.
const_iterator operator+ (ssize_t i) const
Write what the function does here.
const_iterator operator- (ssize_t i) const
Write what the function does here.
ssize_t operator- (const const_iterator &r) const
Write what the function does here.
const const_iterator & operator+= (ssize_t i)
Write what the function does here.
const const_iterator & operator-= (ssize_t i)
Write what the function does here.
const const_iterator & operator++ ()
Write what the function does here.
const const_iterator & operator-- ()
Write what the function does here.
const_iterator operator++ (int)
Write what the function does here.
const_iterator operator-- (int)
Write what the function does here.
bool operator> (const const_iterator &r) const
Write what the function does here.
bool operator>= (const const_iterator &r) const
Write what the function does here.
bool operator< (const const_iterator &r) const
Write what the function does here.
bool operator<= (const const_iterator &r) const
Write what the function does here.
Private Types
typedef vector< float >
*
::const_iterator subIterator
Private Member Functions
const_iterator (subIterator pointIterator, subIterator colorIterator, subIterator textureCoordIterator)
Private Attributes
Triangle tri
subIterator pointIterator
subIterator colorIterator
subIterator textureCoordIterator
Friends
class Mesh_t
const_iterator operator+ (ssize_t i, const const_iterator &iter)
Write what the function does here.
Detailed Description
Write what the function does here.
Parameters
value_type
Triangle
Return values
(variable) (description of variable)
Definition at line 442 of file mesh.h.
Constructor & Destructor Documentation
Mesh_t::const_iterator::const_iterator () [inline]
Write what the function does here.
Return values
(variable) (description of variable)
Definition at line 460 of file mesh.h.
Referenced by operator+().
        {
        }
Member Function Documentation
bool Mesh_t::const_iterator::operator!= (const const_iterator & rt) const [inline]
Write what the function does here.
Parameters
rt
Return values
(variable) (description of variable)
Definition at line 483 of file mesh.h.
        {
            return pointIterator != rt.pointIterator;
        }
const Triangle& Mesh_t::const_iterator::operator* () const [inline]
Write what the function does here.
Return values
(variable) (description of variable)
Definition at line 493 of file mesh.h.
Referenced by operator->().
        {
            subIterator p = pointIterator, c = colorIterator, t = textureCoordIterator;
            tri.p[0] = VectorF(p[0], p[1], p[2]);
            tri.p[1] = VectorF(p[3], p[4], p[5]);
            tri.p[2] = VectorF(p[6], p[7], p[8]);
            tri.c[0] = Color(c[0], c[1], c[2], c[3]);
            tri.c[1] = Color(c[4], c[5], c[6], c[7]);
            tri.c[2] = Color(c[8], c[9], c[10], c[11]);
            tri.t[0] = TextureCoord(t[0], t[1]);
            tri.t[1] = TextureCoord(t[2], t[3]);
            tri.t[2] = TextureCoord(t[4], t[5]);
            return tri;
        }
const_iterator Mesh_t::const_iterator::operator+ (ssize_t i) const [inline]
Write what the function does here.
Parameters
i
Return values
(variable) (description of variable)
Definition at line 537 of file mesh.h.
References const_iterator().
Referenced by operator+=(), operator-(), and operator[]().
        {
            return const_iterator(pointIterator + i * floatsPerPoint * pointsPerTriangle,
                    colorIterator + i * floatsPerColor * colorsPerTriangle,
                    textureCoordIterator + i * floatsPerTextureCoord * textureCoordsPerTriangle);
        }
const const_iterator& Mesh_t::const_iterator::operator++ () [inline]
Write what the function does here.
Return values
(variable) (description of variable)
Definition at line 610 of file mesh.h.
References operator+=().
Referenced by operator++().
        {
            return operator +=(1);
        }
const_iterator Mesh_t::const_iterator::operator++ (int) [inline]
Write what the function does here.
Parameters
int
Return values
(variable) (description of variable)
Definition at line 632 of file mesh.h.
References operator++().
        {
            const_iterator retval = *this;
            operator ++();
            return retval;
        }
const const_iterator& Mesh_t::const_iterator::operator+= (ssize_t i) [inline]
Write what the function does here.
Parameters
i
Return values
(variable) (description of variable)
Definition at line 588 of file mesh.h.
References operator+().
Referenced by operator++().
        {
            return *this = operator +(i);
        }
const_iterator Mesh_t::const_iterator::operator- (ssize_t i) const [inline]
Write what the function does here.
Parameters
i
Return values
(variable) (description of variable)
Definition at line 564 of file mesh.h.
References operator+().
Referenced by operator-=().
        {
            return operator +(-i);
        }
ssize_t Mesh_t::const_iterator::operator- (const const_iterator & r) const [inline]
Write what the function does here.
Parameters
r
Return values
(variable) (description of variable)
Definition at line 576 of file mesh.h.
        {
            return (textureCoordIterator - r.textureCoordIterator) / (floatsPerTextureCoord *
      textureCoordsPerTriangle);
        }
const const_iterator& Mesh_t::const_iterator::operator-- () [inline]
Write what the function does here.
Return values
(variable) (description of variable)
Definition at line 620 of file mesh.h.
References operator-=().
Referenced by operator--().
        {
            return operator -=(1);
        }
const_iterator Mesh_t::const_iterator::operator-- (int) [inline]
Write what the function does here.
Parameters
int
Return values
(variable) (description of variable)
Definition at line 646 of file mesh.h.
References operator--().
        {
            const_iterator retval = *this;
            operator --();
            return retval;
        }
const const_iterator& Mesh_t::const_iterator::operator-= (ssize_t i) [inline]
Write what the function does here.
Parameters
i
Return values
(variable) (description of variable)
Definition at line 600 of file mesh.h.
References operator-().
Referenced by operator--().
        {
            return *this = operator -(i);
        }
const Triangle* Mesh_t::const_iterator::operator-> () const [inline]
Write what the function does here.
Return values
(variable) (description of variable)
Definition at line 525 of file mesh.h.
References operator*().
        {
            return &operator *();
        }
bool Mesh_t::const_iterator::operator< (const const_iterator & r) const [inline]
Write what the function does here.
Parameters
r
Return values
(variable) (description of variable)
Definition at line 684 of file mesh.h.
        {
            return pointIterator < r.pointIterator;
        }
bool Mesh_t::const_iterator::operator<= (const const_iterator & r) const [inline]
Write what the function does here.
Parameters
r
Return values
(variable) (description of variable)
Definition at line 696 of file mesh.h.
        {
            return pointIterator <= r.pointIterator;
        }
bool Mesh_t::const_iterator::operator== (const const_iterator & rt) const [inline]
Write what the function does here.
Parameters
rt
Return values
(variable) (description of variable)
Definition at line 471 of file mesh.h.
        {
            return pointIterator == rt.pointIterator;
        }
bool Mesh_t::const_iterator::operator> (const const_iterator & r) const [inline]
Write what the function does here.
Parameters
r
Return values
(variable) (description of variable)
Definition at line 660 of file mesh.h.
        {
            return pointIterator > r.pointIterator;
        }
bool Mesh_t::const_iterator::operator>= (const const_iterator & r) const [inline]
Write what the function does here.
Parameters
r
Return values
(variable) (description of variable)
Definition at line 672 of file mesh.h.
        {
            return pointIterator >= r.pointIterator;
        }
const Triangle& Mesh_t::const_iterator::operator[] (ssize_t index) const [inline]
Write what the function does here.
Parameters
index
Return values
(variable) (description of variable)
Definition at line 515 of file mesh.h.
References operator+().
        {
            return operator +(index).operator * ();
        }
Friends And Related Function Documentation
const_iterator operator+ (ssize_t i, const const_iterator & iter) [friend]
Write what the function does here.
Parameters
i
iter
Return values
(variable) (description of variable)
Definition at line 552 of file mesh.h.
        {
            return iter.operator + (i);
        }
The documentation for this class was generated from the following file:
mesh.h