circularDeque< T, arraySize > Class Template Reference
Write what the function does here.
#include <util.h>
Classes
class const_iterator
Write what the function does here.
class iterator
Write what the function does here.
Public Types
typedef T value_type
typedef size_t size_type
typedef ptrdiff_t difference_type
typedef T & reference
typedef const T & const_reference
typedef T * pointer
typedef const T * const_pointer
typedef std::reverse_iterator
*
< iterator > reverse_iterator
typedef std::reverse_iterator
*
< const_iterator > const_reverse_iterator
Public Member Functions
iterator begin ()
Write what the function does here.
const_iterator begin () const
Write what the function does here.
const_iterator cbegin () const
Write what the function does here.
iterator end ()
Write what the function does here.
const_iterator end () const
Write what the function does here.
const_iterator cend () const
Write what the function does here.
reverse_iterator rbegin ()
Write what the function does here.
const_reverse_iterator rbegin () const
Write what the function does here.
const_reverse_iterator crbegin () const
Write what the function does here.
reverse_iterator rend ()
Write what the function does here.
const_reverse_iterator rend () const
Write what the function does here.
const_reverse_iterator crend () const
Write what the function does here.
T & front ()
Write what the function does here.
const T & front () const
Write what the function does here.
T & back ()
Write what the function does here.
const T & back () const
Write what the function does here.
size_type size () const
Write what the function does here.
T & at (size_type pos)
Write what the function does here.
const T & at (size_type pos) const
Write what the function does here.
T & operator[] (size_type pos)
Write what the function does here.
const T & operator[] (size_type pos) const
Write what the function does here.
bool empty () const
Write what the function does here.
void push_front (const T &v)
Write what the function does here.
void push_front (T &&v)
Write what the function does here.
void push_back (const T &v)
Write what the function does here.
void push_back (T &&v)
Write what the function does here.
void swap (circularDeque &other)
Write what the function does here.
Static Public Member Functions
static constexpr size_type capacity ()
Write what the function does here.
Private Attributes
size_type frontIndex
size_type backIndex
value_type array [arraySize]
Friends
class iterator
class const_iterator
Detailed Description
template<typename T, size_t arraySize>class circularDeque< T, arraySize >
Write what the function does here.
Return values
(variable) (description of variable)
Definition at line 231 of file util.h.
Member Function Documentation
template<typename T, size_t arraySize> T& circularDeque< T, arraySize >::at (size_type pos) [inline]
Write what the function does here.
Parameters
pos
Return values
(variable) (description of variable)
Definition at line 1092 of file util.h.
        {
            if(pos >= size())
            {
                throw out_of_range("position out of range in circularDeque::at");
            }
            return begin()[pos];
        }
template<typename T, size_t arraySize> const T& circularDeque< T, arraySize >::at (size_type pos) const [inline]
Write what the function does here.
Parameters
pos
Return values
(variable) (description of variable)
Definition at line 1109 of file util.h.
        {
            if(pos >= size())
            {
                throw out_of_range("position out of range in circularDeque::at");
            }
            return cbegin()[pos];
        }
template<typename T, size_t arraySize> T& circularDeque< T, arraySize >::back () [inline]
Write what the function does here.
Return values
(variable) (description of variable)
Definition at line 1060 of file util.h.
        {
            return end()[-1];
        }
template<typename T, size_t arraySize> const T& circularDeque< T, arraySize >::back () const [inline]
Write what the function does here.
Return values
(variable) (description of variable)
Definition at line 1070 of file util.h.
        {
            return end()[-1];
        }
template<typename T, size_t arraySize> iterator circularDeque< T, arraySize >::begin () [inline]
Write what the function does here.
Return values
(variable) (description of variable)
Definition at line 920 of file util.h.
Referenced by circularDeque< uint_fast8_t, bufferSize+1 >::at(), circularDeque< uint_fast8_t, bufferSize+1 >::front(), circularDeque< uint_fast8_t, bufferSize+1 >::operator[](), and circularDeque< uint_fast8_t, bufferSize+1 >::rend().
        {
            return iterator(this, frontIndex);
        }
template<typename T, size_t arraySize> const_iterator circularDeque< T, arraySize >::begin () const [inline]
Write what the function does here.
Return values
(variable) (description of variable)
Definition at line 930 of file util.h.
        {
            return const_iterator(this, frontIndex);
        }
template<typename T, size_t arraySize> static constexpr size_type circularDeque< T, arraySize >::capacity () [inline], [static]
Write what the function does here.
Return values
(variable) (description of variable)
Definition at line 247 of file util.h.
        {
            return arraySize;
        }
template<typename T, size_t arraySize> const_iterator circularDeque< T, arraySize >::cbegin () const [inline]
Write what the function does here.
Return values
(variable) (description of variable)
Definition at line 940 of file util.h.
Referenced by circularDeque< uint_fast8_t, bufferSize+1 >::at(), circularDeque< uint_fast8_t, bufferSize+1 >::crend(), circularDeque< uint_fast8_t, bufferSize+1 >::operator[](), circularDeque< uint_fast8_t, bufferSize+1 >::rend(), and circularDeque< uint_fast8_t, bufferSize+1 >::size().
        {
            return const_iterator(this, frontIndex);
        }
template<typename T, size_t arraySize> const_iterator circularDeque< T, arraySize >::cend () const [inline]
Write what the function does here.
Return values
(variable) (description of variable)
Definition at line 970 of file util.h.
Referenced by circularDeque< uint_fast8_t, bufferSize+1 >::crbegin(), circularDeque< uint_fast8_t, bufferSize+1 >::rbegin(), and circularDeque< uint_fast8_t, bufferSize+1 >::size().
        {
            return const_iterator(this, backIndex);
        }
template<typename T, size_t arraySize> const_reverse_iterator circularDeque< T, arraySize >::crbegin () const [inline]
Write what the function does here.
Return values
(variable) (description of variable)
Definition at line 1000 of file util.h.
        {
            return const_reverse_iterator(cend());
        }
template<typename T, size_t arraySize> const_reverse_iterator circularDeque< T, arraySize >::crend () const [inline]
Write what the function does here.
Return values
(variable) (description of variable)
Definition at line 1030 of file util.h.
        {
            return const_reverse_iterator(cbegin());
        }
template<typename T, size_t arraySize> bool circularDeque< T, arraySize >::empty () const [inline]
Write what the function does here.
Return values
(variable) (description of variable)
Definition at line 1148 of file util.h.
        {
            return frontIndex == backIndex;
        }
template<typename T, size_t arraySize> iterator circularDeque< T, arraySize >::end () [inline]
Write what the function does here.
Return values
(variable) (description of variable)
Definition at line 950 of file util.h.
Referenced by circularDeque< uint_fast8_t, bufferSize+1 >::back(), and circularDeque< uint_fast8_t, bufferSize+1 >::rbegin().
        {
            return iterator(this, backIndex);
        }
template<typename T, size_t arraySize> const_iterator circularDeque< T, arraySize >::end () const [inline]
Write what the function does here.
Return values
(variable) (description of variable)
Definition at line 960 of file util.h.
        {
            return const_iterator(this, backIndex);
        }
template<typename T, size_t arraySize> T& circularDeque< T, arraySize >::front () [inline]
Write what the function does here.
Return values
(variable) (description of variable)
Definition at line 1040 of file util.h.
        {
            return *begin();
        }
template<typename T, size_t arraySize> const T& circularDeque< T, arraySize >::front () const [inline]
Write what the function does here.
Return values
(variable) (description of variable)
Definition at line 1050 of file util.h.
        {
            return *begin();
        }
template<typename T, size_t arraySize> T& circularDeque< T, arraySize >::operator[] (size_type pos) [inline]
Write what the function does here.
Parameters
pos
Return values
(variable) (description of variable)
Definition at line 1126 of file util.h.
        {
            return begin()[pos];
        }
template<typename T, size_t arraySize> const T& circularDeque< T, arraySize >::operator[] (size_type pos) const [inline]
Write what the function does here.
Parameters
pos
Return values
(variable) (description of variable)
Definition at line 1138 of file util.h.
        {
            return cbegin()[pos];
        }
template<typename T, size_t arraySize> void circularDeque< T, arraySize >::push_back (const T & v) [inline]
Write what the function does here.
Parameters
v
Definition at line 1196 of file util.h.
        {
            array[backIndex] = v;
            if(++backIndex >= arraySize)
            {
                backIndex = 0;
            }
        }
template<typename T, size_t arraySize> void circularDeque< T, arraySize >::push_back (T && v) [inline]
Write what the function does here.
Parameters
v
Definition at line 1211 of file util.h.
        {
            array[backIndex] = move(v);
            if(++backIndex >= arraySize)
            {
                backIndex = 0;
            }
        }
template<typename T, size_t arraySize> void circularDeque< T, arraySize >::push_front (const T & v) [inline]
Write what the function does here.
void clear() { frontIndex = backIndex = 0; }
/** Write what the function does here
Parameters
v
Definition at line 1166 of file util.h.
        {
            if(frontIndex-- == 0)
            {
                frontIndex = arraySize - 1;
            }
            array[frontIndex] = v;
        }
template<typename T, size_t arraySize> void circularDeque< T, arraySize >::push_front (T && v) [inline]
Write what the function does here.
Parameters
v
Definition at line 1181 of file util.h.
        {
            if(frontIndex-- == 0)
            {
                frontIndex = arraySize - 1;
            }
            array[frontIndex] = move(v);
        }
template<typename T, size_t arraySize> reverse_iterator circularDeque< T, arraySize >::rbegin () [inline]
Write what the function does here.
Return values
(variable) (description of variable)
Definition at line 980 of file util.h.
        {
            return reverse_iterator(end());
        }
template<typename T, size_t arraySize> const_reverse_iterator circularDeque< T, arraySize >::rbegin () const [inline]
Write what the function does here.
Return values
(variable) (description of variable)
Definition at line 990 of file util.h.
        {
            return const_reverse_iterator(cend());
        }
template<typename T, size_t arraySize> reverse_iterator circularDeque< T, arraySize >::rend () [inline]
Write what the function does here.
Return values
(variable) (description of variable)
Definition at line 1010 of file util.h.
        {
            return reverse_iterator(begin());
        }
template<typename T, size_t arraySize> const_reverse_iterator circularDeque< T, arraySize >::rend () const [inline]
Write what the function does here.
Return values
(variable) (description of variable)
Definition at line 1020 of file util.h.
        {
            return const_reverse_iterator(cbegin());
        }
template<typename T, size_t arraySize> size_type circularDeque< T, arraySize >::size () const [inline]
Write what the function does here.
Return values
(variable) (description of variable)
Definition at line 1080 of file util.h.
Referenced by circularDeque< uint_fast8_t, bufferSize+1 >::at().
        {
            return cend() - cbegin();
        }
template<typename T, size_t arraySize> void circularDeque< T, arraySize >::swap (circularDeque< T, arraySize > & other) [inline]
Write what the function does here.
void pop_front() { array[frontIndex] = T();
if(++frontIndex >= arraySize) { frontIndex = 0; } }
/** Write what the function does here
void pop_back() {
if(backIndex-- == 0) { backIndex = arraySize - 1; } array[backIndex] = T(); }
/** Write what the function does here
Parameters
other
Definition at line 1252 of file util.h.
        {
            circularDeque<T, arraySize> temp = move(*this);
            *this = move(other);
            other = move(temp);
        }
The documentation for this class was generated from the following file:
util.h