Mesh_t Class Reference
Write what the function does here.
#include <mesh.h>
Classes
class const_iterator
Write what the function does here.
Public Types
typedef std::reverse_iterator
*
< const_iterator > const_reverse_iterator
Public Member Functions
Mesh_t ()
Write what the function does here.
Mesh_t (Image texture, vector< Triangle > triangles=vector< Triangle >())
Write what the function does here.
Mesh_t (TextureDescriptor tex, vector< Triangle > triangles=vector< Triangle >())
Write what the function does here.
Mesh_t (const TransformedMesh &tm)
const Image & texture () const
Write what the function does here.
size_t size () const
Write what the function does here.
const_iterator begin () const
Write what the function does here.
const_iterator end () const
Write what the function does here.
const_iterator cbegin () const
Write what the function does here.
const_iterator cend () const
Write what the function does here.
const_reverse_iterator rbegin () const
Write what the function does here.
const_reverse_iterator rend () const
Write what the function does here.
const_reverse_iterator crbegin () const
Write what the function does here.
const_reverse_iterator crend () const
Write what the function does here.
void add (const Mesh_t &m)
Write what the function does here.
void add (Mesh m)
Write what the function does here.
void add (TransformedMesh m)
Write what the function does here.
Private Attributes
vector< float > points
vector< float > colors
vector< float > textureCoords
Image textureInternal
size_t length
Static Private Attributes
static constexpr size_t floatsPerPoint = 3
static constexpr size_t pointsPerTriangle = 3
static constexpr size_t floatsPerColor = 4
static constexpr size_t colorsPerTriangle = 3
static constexpr size_t floatsPerTextureCoord = 2
static constexpr size_t textureCoordsPerTriangle = 3
Friends
class Renderer
class const_iterator
Mesh interpolateColors (Mesh dest, Mesh mesh, Color cNXNYNZ, Color cNXNYPZ, Color cNXPYNZ, Color cNXPYPZ, Color cPXNYNZ, Color cPXNYPZ, Color cPXPYNZ, Color cPXPYPZ)
Write what the function does here.
Mesh interpolateColors (Mesh mesh, Color cNXNYNZ, Color cNXNYPZ, Color cNXPYNZ, Color cNXPYPZ, Color cPXNYNZ, Color cPXNYPZ, Color cPXPYNZ, Color cPXPYPZ)
Write what the function does here.
Mesh lightColors (Mesh dest, Mesh mesh, VectorF lightDir, float ambient, float diffuse)
Detailed Description
Write what the function does here.
Return values
(variable) (description of variable)
Definition at line 230 of file mesh.h.
Constructor & Destructor Documentation
Mesh_t::Mesh_t () [inline]
Write what the function does here.
Parameters
reader
client
Return values
(variable) (description of variable) Write what the function does here
(variable) (description of variable)
Definition at line 284 of file mesh.h.
        {
            length = 0;
        }
Mesh_t::Mesh_t (Image texture, vector< Triangle > triangles = vector<Triangle>()) [inline]
Write what the function does here.
Parameters
texture
Return values
(variable) (description of variable)
Definition at line 296 of file mesh.h.
References texture().
        {
            length = triangles.size();
            points.reserve(floatsPerPoint * pointsPerTriangle * length);
            colors.reserve(floatsPerColor * colorsPerTriangle * length);
            textureCoords.reserve(floatsPerTextureCoord * textureCoordsPerTriangle * length);
            textureInternal = texture;
            for(Triangle tri : triangles)
            {
                points.push_back(tri.p[0].x);
                points.push_back(tri.p[0].y);
                points.push_back(tri.p[0].z);
                points.push_back(tri.p[1].x);
                points.push_back(tri.p[1].y);
                points.push_back(tri.p[1].z);
                points.push_back(tri.p[2].x);
                points.push_back(tri.p[2].y);
                points.push_back(tri.p[2].z);
                colors.push_back(tri.c[0].r);
                colors.push_back(tri.c[0].g);
                colors.push_back(tri.c[0].b);
                colors.push_back(tri.c[0].a);
                colors.push_back(tri.c[1].r);
                colors.push_back(tri.c[1].g);
                colors.push_back(tri.c[1].b);
                colors.push_back(tri.c[1].a);
                colors.push_back(tri.c[2].r);
                colors.push_back(tri.c[2].g);
                colors.push_back(tri.c[2].b);
                colors.push_back(tri.c[2].a);
                textureCoords.push_back(tri.t[0].u);
                textureCoords.push_back(tri.t[0].v);
                textureCoords.push_back(tri.t[1].u);
                textureCoords.push_back(tri.t[1].v);
                textureCoords.push_back(tri.t[2].u);
                textureCoords.push_back(tri.t[2].v);
            }
        }
Mesh_t::Mesh_t (TextureDescriptor tex, vector< Triangle > triangles = vector<Triangle>()) [inline]
Write what the function does here.
Parameters
tex
Return values
(variable) (description of variable)
Definition at line 343 of file mesh.h.
        {
            length = triangles.size();
            points.reserve(floatsPerPoint * pointsPerTriangle * length);
            colors.reserve(floatsPerColor * colorsPerTriangle * length);
            textureCoords.reserve(floatsPerTextureCoord * textureCoordsPerTriangle * length);
            textureInternal = tex.image;
            for(Triangle tri : triangles)
            {
                points.push_back(tri.p[0].x);
                points.push_back(tri.p[0].y);
                points.push_back(tri.p[0].z);
                points.push_back(tri.p[1].x);
                points.push_back(tri.p[1].y);
                points.push_back(tri.p[1].z);
                points.push_back(tri.p[2].x);
                points.push_back(tri.p[2].y);
                points.push_back(tri.p[2].z);
                colors.push_back(tri.c[0].r);
                colors.push_back(tri.c[0].g);
                colors.push_back(tri.c[0].b);
                colors.push_back(tri.c[0].a);
                colors.push_back(tri.c[1].r);
                colors.push_back(tri.c[1].g);
                colors.push_back(tri.c[1].b);
                colors.push_back(tri.c[1].a);
                colors.push_back(tri.c[2].r);
                colors.push_back(tri.c[2].g);
                colors.push_back(tri.c[2].b);
                colors.push_back(tri.c[2].a);
                textureCoords.push_back(interpolate(tri.t[0].u, tex.minU, tex.maxU));
                textureCoords.push_back(interpolate(tri.t[0].v, tex.minV, tex.maxV));
                textureCoords.push_back(interpolate(tri.t[1].u, tex.minU, tex.maxU));
                textureCoords.push_back(interpolate(tri.t[1].v, tex.minV, tex.maxV));
                textureCoords.push_back(interpolate(tri.t[2].u, tex.minU, tex.maxU));
                textureCoords.push_back(interpolate(tri.t[2].v, tex.minV, tex.maxV));
            }
        }
Member Function Documentation
void Mesh_t::add (const Mesh_t & m) [inline]
Write what the function does here.
Parameters
m
Definition at line 798 of file mesh.h.
References texture().
Referenced by add().
        {
            if(texture())
            {
                if(m.texture() && m.texture() != texture())
                {
                    throw ImageNotSameException();
                }
            }
            else
            {
                textureInternal = m.texture();
            }
            length += m.length;
            points.insert(points.end(), m.points.begin(), m.points.end());
            colors.insert(colors.end(), m.colors.begin(), m.colors.end());
            textureCoords.insert(textureCoords.end(), m.textureCoords.begin(), m.textureCoords.end());
        }
void Mesh_t::add (Mesh m) [inline]
Write what the function does here.
Parameters
m
Definition at line 825 of file mesh.h.
References add().
        {
            add(*m);
        }
void Mesh_t::add (TransformedMesh m) [inline]
Write what the function does here.
Parameters
m
Definition at line 835 of file mesh.h.
References add().
        {
            Mesh_t m2(m);
            add(m2);
        }
const_iterator Mesh_t::begin () const [inline]
Write what the function does here.
Return values
(variable) (description of variable)
Definition at line 718 of file mesh.h.
Referenced by crend(), and rend().
        {
            return const_iterator(points.begin(), colors.begin(), textureCoords.begin());
        }
const_iterator Mesh_t::cbegin () const [inline]
Write what the function does here.
Return values
(variable) (description of variable)
Definition at line 738 of file mesh.h.
        {
            return const_iterator(points.begin(), colors.begin(), textureCoords.begin());
        }
const_iterator Mesh_t::cend () const [inline]
Write what the function does here.
Return values
(variable) (description of variable)
Definition at line 748 of file mesh.h.
        {
            return const_iterator(points.end(), colors.end(), textureCoords.end());
        }
const_reverse_iterator Mesh_t::crbegin () const [inline]
Write what the function does here.
Return values
(variable) (description of variable)
Definition at line 778 of file mesh.h.
References end().
        {
            return const_reverse_iterator(end());
        }
const_reverse_iterator Mesh_t::crend () const [inline]
Write what the function does here.
Return values
(variable) (description of variable)
Definition at line 788 of file mesh.h.
References begin().
        {
            return const_reverse_iterator(begin());
        }
const_iterator Mesh_t::end () const [inline]
Write what the function does here.
Return values
(variable) (description of variable)
Definition at line 728 of file mesh.h.
Referenced by crbegin(), and rbegin().
        {
            return const_iterator(points.end(), colors.end(), textureCoords.end());
        }
const_reverse_iterator Mesh_t::rbegin () const [inline]
Write what the function does here.
Return values
(variable) (description of variable)
Definition at line 758 of file mesh.h.
References end().
        {
            return const_reverse_iterator(end());
        }
const_reverse_iterator Mesh_t::rend () const [inline]
Write what the function does here.
Return values
(variable) (description of variable)
Definition at line 768 of file mesh.h.
References begin().
        {
            return const_reverse_iterator(begin());
        }
size_t Mesh_t::size () const [inline]
Write what the function does here.
Return values
(variable) (description of variable)
Definition at line 708 of file mesh.h.
        {
            return length;
        }
const Image& Mesh_t::texture () const [inline]
Write what the function does here.
Return values
(variable) (description of variable)
Definition at line 428 of file mesh.h.
Referenced by add(), and Mesh_t().
        {
            return textureInternal;
        }
Friends And Related Function Documentation
Mesh interpolateColors (Mesh dest, Mesh mesh, Color cNXNYNZ, Color cNXNYPZ, Color cNXPYNZ, Color cNXPYPZ, Color cPXNYNZ, Color cPXNYPZ, Color cPXPYNZ, Color cPXPYPZ) [friend]
Write what the function does here.
Parameters
dest
mesh
cNXNYNZ
cNXNYPZ
cNXPYNZ
cNXPYPZ
cPXNYNZ
cPXNYPZ
cPXPYNZ
cPXPYPZ
Return values
(variable) (description of variable)
Definition at line 863 of file mesh.h.
{
    assert(dest && mesh);
    if(dest->texture())
    {
        if(mesh->texture() && mesh->texture() != dest->texture())
        {
            throw ImageNotSameException();
        }
    }
    else
    {
        dest->textureInternal = mesh->texture();
    }
    dest->length += mesh->length;
    dest->textureCoords.insert(dest->textureCoords.end(), mesh->textureCoords.begin(), mesh->textureCoords.
      end());
    size_t vi = 0, ci = 0;
    for(size_t i = 0; i < mesh->length; i++)
    {
        float x = mesh->points[vi++];
        float y = mesh->points[vi++];
        float z = mesh->points[vi++];
        dest->points.push_back(x);
        dest->points.push_back(y);
        dest->points.push_back(z);
        Color c;
        c.r = mesh->colors[ci++];
        c.g = mesh->colors[ci++];
        c.b = mesh->colors[ci++];
        c.a = mesh->colors[ci++];
        c = scale(c, interpolate(x, interpolate(y, interpolate(z, cNXNYNZ, cNXNYPZ), interpolate(z, cNXPYNZ
      , cNXPYPZ)), interpolate(y, interpolate(z, cPXNYNZ, cPXNYPZ), interpolate(z, cPXPYNZ, cPXPYPZ))));
        dest->colors.push_back(c.r);
        dest->colors.push_back(c.g);
        dest->colors.push_back(c.b);
        dest->colors.push_back(c.a);
    }
    return dest;
}
Mesh interpolateColors (Mesh mesh, Color cNXNYNZ, Color cNXNYPZ, Color cNXPYNZ, Color cNXPYPZ, Color cPXNYNZ, Color cPXNYPZ, Color cPXPYNZ, Color cPXPYPZ) [friend]
Write what the function does here.
Parameters
mesh
cNXNYNZ
cNXNYPZ
cNXPYNZ
cNXPYPZ
cPXNYNZ
cPXNYPZ
cPXPYNZ
cPXPYPZ
Return values
(variable) (description of variable)
Definition at line 921 of file mesh.h.
{
    assert(mesh);
    Mesh dest = Mesh(new Mesh_t);
    dest->textureInternal = mesh->texture();
    dest->length += mesh->length;
    dest->textureCoords.insert(dest->textureCoords.end(), mesh->textureCoords.begin(), mesh->textureCoords.
      end());
    size_t vi = 0, ci = 0;
    for(size_t i = 0; i < mesh->length; i++)
    {
        float x = mesh->points[vi++];
        float y = mesh->points[vi++];
        float z = mesh->points[vi++];
        dest->points.push_back(x);
        dest->points.push_back(y);
        dest->points.push_back(z);
        Color c;
        c.r = mesh->colors[ci++];
        c.g = mesh->colors[ci++];
        c.b = mesh->colors[ci++];
        c.a = mesh->colors[ci++];
        c = scale(c, interpolate(x, interpolate(y, interpolate(z, cNXNYNZ, cNXNYPZ), interpolate(z, cNXPYNZ
      , cNXPYPZ)), interpolate(y, interpolate(z, cPXNYNZ, cPXNYPZ), interpolate(z, cPXPYNZ, cPXPYPZ))));
        dest->colors.push_back(c.r);
        dest->colors.push_back(c.g);
        dest->colors.push_back(c.b);
        dest->colors.push_back(c.a);
    }
    return dest;
}
The documentation for this class was generated from the following file:
mesh.h