Generate Namespace Reference
Write what the function does here.
Functions
Mesh quadrilateral (TextureDescriptor texture, VectorF p1, Color c1, VectorF p2, Color c2, VectorF p3, Color c3, VectorF p4, Color c4)
Write what the function does here.
Mesh unitBox (TextureDescriptor nx, TextureDescriptor px, TextureDescriptor ny, TextureDescriptor py, TextureDescriptor nz, TextureDescriptor pz)
make a box from <0, 0, 0> to <1, 1, 1>
Mesh line (const vector< VectorF > &linePoints, TextureDescriptor texture, Color color, float lineWidth)
Detailed Description
Write what the function does here.
Returns
Function Documentation
Mesh Generate::quadrilateral (TextureDescriptor texture, VectorF p1, Color c1, VectorF p2, Color c2, VectorF p3, Color c3, VectorF p4, Color c4) [inline]
Write what the function does here.
Parameters
texture
p1
c1
p2
c2
p3
c3
p4
c4
Returns
Write what the function does here
Parameters
minU
maxV
Returns
Definition at line 240 of file generate.h.
References quadrilateral().
Referenced by quadrilateral(), and unitBox().
    {
        const TextureCoord t1 = TextureCoord(texture.minU, texture.minV);
        const TextureCoord t2 = TextureCoord(texture.maxU, texture.minV);
        const TextureCoord t3 = TextureCoord(texture.maxU, texture.maxV);
        /**
         * @brief Write what the function does here
         *
         * @param minU
         * @param maxV
         *
         * @return
         **/
        const TextureCoord t4 = TextureCoord(texture.minU, texture.maxV);
        return Mesh(new Mesh_t(texture.image, vector<Triangle> {Triangle(p1, c1, t1, p2, c2, t2, p3,
      c3, t3), Triangle(p3, c3, t3, p4, c4, t4, p1, c1, t1)}));
    }
Mesh Generate::unitBox (TextureDescriptor nx, TextureDescriptor px, TextureDescriptor ny, TextureDescriptor py, TextureDescriptor nz, TextureDescriptor pz) [inline]
make a box from <0, 0, 0> to <1, 1, 1>
Write what the function does here
Parameters
nx
px
ny
py
nz
pz
Returns
Write what the function does here
Parameters
nx
Returns
Write what the function does here
Parameters
px
Returns
Write what the function does here
Parameters
ny
Returns
Write what the function does here
Parameters
py
Returns
Write what the function does here
Parameters
nz
Returns
Write what the function does here
Parameters
pz
Returns
Definition at line 271 of file generate.h.
References quadrilateral(), and unitBox().
Referenced by unitBox().
    {
        const VectorF p0 = VectorF(0, 0, 0);
        const VectorF p1 = VectorF(1, 0, 0);
        const VectorF p2 = VectorF(0, 1, 0);
        const VectorF p3 = VectorF(1, 1, 0);
        const VectorF p4 = VectorF(0, 0, 1);
        const VectorF p5 = VectorF(1, 0, 1);
        const VectorF p6 = VectorF(0, 1, 1);
        const VectorF p7 = VectorF(1, 1, 1);
        Mesh retval = Mesh(new Mesh_t());
        const Color c = Color(1);
        /**
         * @brief Write what the function does here
         *
         * @param nx
         *
         * @return
         **/
        if(nx)
        {
            retval->add(quadrilateral(nx,
                        p0, c,
                        p4, c,
                        p6, c,
                        p2, c
                        ));
        }
        /**
         * @brief Write what the function does here
         *
         * @param px
         *
         * @return
         **/
        if(px)
        {
            retval->add(quadrilateral(px,
                        p5, c,
                        p1, c,
                        p3, c,
                        p7, c
                        ));
        }
        /**
         * @brief Write what the function does here
         *
         * @param ny
         *
         * @return
         **/
        if(ny)
        {
            retval->add(quadrilateral(ny,
                        p0, c,
                        p1, c,
                        p5, c,
                        p4, c
                        ));
        }
        /**
         * @brief Write what the function does here
         *
         * @param py
         *
         * @return
         **/
        if(py)
        {
            retval->add(quadrilateral(py,
                        p6, c,
                        p7, c,
                        p3, c,
                        p2, c
                        ));
        }
        /**
         * @brief Write what the function does here
         *
         * @param nz
         *
         * @return
         **/
        if(nz)
        {
            retval->add(quadrilateral(nz,
                        p1, c,
                        p0, c,
                        p2, c,
                        p3, c
                        ));
        }
        /**
         * @brief Write what the function does here
         *
         * @param pz
         *
         * @return
         **/
        if(pz)
        {
            retval->add(quadrilateral(pz,
                        p4, c,
                        p5, c,
                        p7, c,
                        p6, c
                        ));
        }
        return retval;
    }